name: autoDeploy

on:
  workflow_run:
    workflows:
      - "Feature Branch CI"
    types:
      - completed
  push:
    branches:
      - develop
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 조건 확인
      - name: Run only if both conditions are met
        if: >
          github.event_name == 'workflow_run' &&
          github.event.workflow_run.head_branch == 'develop'
        run: echo "Both conditions met! Running workflow..."

      # 0. env 초기화
      - name: Reset .env file
        run: echo "" > .env

      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. .env 파일 생성
      - name: Create .env file
        run: |
          echo REACT_APP_TMDB_API_KEY=${{ secrets.REACT_APP_TMDB_API_KEY }} >> .env
          echo REACT_APP_KAKAO_JS_KEY=${{ secrets.REACT_APP_KAKAO_JS_KEY }} >> .env
          echo REACT_APP_KAKAO_SDK_INTEGRITY=${{ secrets.REACT_APP_KAKAO_SDK_INTEGRITY }} >> .env
          echo REACT_APP_REDIRECT_URI=${{ secrets.REACT_APP_REDIRECT_URI }} >> .env
          echo REACT_APP_REST_API_KEY=${{ secrets.REACT_APP_REST_API_KEY }} >> .env

      # 3. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 4. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 5. 빌드 실행
      - name: Build project
        run: npm run build

      # 6. gh-pages 브랜치로 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true

      # 7. branch 정보 가져오기
      - name: Fetch all branches
        run: git fetch --all

      # 8. Develop 브랜치를 Main 브랜치에 강제 Push
      - name: Force Push Develop to Main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout develop
          git push origin develop:main --force
