name: autoDeploy

on:
  workflow_run:
    workflows:
      - "Feature Branch CI"
    types:
      - completed
  push:
    branches:
      - develop
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run only if both conditions are met
        if: >
          github.event_name == 'workflow_run' &&
          github.event.workflow_run.head_branch == 'develop'
        run: echo "Both conditions met! Running workflow..."

      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Node.js 버전

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. 빌드 실행
      - name: Build project
        env:
          REACT_APP_TMDB_API_KEY: ${{ secrets.REACT_APP_TMDB_API_KEY }}
          REACT_APP_KAKAO_JS_KEY: ${{ secrets.REACT_APP_KAKAO_JS_KEY }}
          REACT_APP_KAKAO_SDK_INTEGRITY: ${{ secrets.REACT_APP_KAKAO_SDK_INTEGRITY }}
          REACT_APP_REDIRECT_URI: ${{ secrets.REACT_APP_REDIRECT_URI }}
        run: |
          if [ -z "${REACT_APP_TMDB_API_KEY}" ] || [ -z "${REACT_APP_KAKAO_JS_KEY}" ] || [ -z "${REACT_APP_KAKAO_SDK_INTEGRITY}" ] || [ -z "${REACT_APP_REDIRECT_URI}" ]; then
            echo "Error: One or more environment variables are missing."
            exit 1
          fi
          npm run build

      # 5. gh-pages 브랜치로 배포
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub 제공 토큰
          publish_dir: ./build # 빌드된 정적 파일 경로
          force_orphan: true # gh-pages 브랜치를 비어있는 상태로 시작


      # 6. branch 정보 가져오기
      - name: Fetch all branches
        run: git fetch --all

      # 7. Develop 브랜치를 Main 브랜치에 강제 Push
      - name: Force Push Develop to Main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout develop
          git push origin develop:main --force
