name: Merge Feature to Develop

on:
  push:
    branches:
      - "feature/**"

jobs:
  merge_to_develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge Feature to Develop
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout develop
          git merge ${{ github.ref_name }} --no-ff --no-edit -X theirs || true
          git push origin develop
