name: Feature Branch CI

on:
  push:
    branches:
      - "feature/**"

jobs:
  code-check-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Merge into develop
        if: success()
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          if git fetch origin develop:develop; then
            echo "Develop branch found and fetched."
          else
            echo "Develop branch not found. Creating develop branch."
            git checkout -b develop
            git push origin develop
          fi

          git checkout develop
          git merge ${{ github.ref_name }} --no-ff --no-edit || true
          git push origin develop --force

